### ISSUE TITLE
Is it possible to add onFocus support ?

### ISSUE THREAD

**Issue by redasakhi** [SaiSurya9999/NgTagInputLibrary#1]
Hi,

I've just tried using this package and thanks for the easy integration and usage.

I am wondering if it's on the road map to add more events such as onFocus to show typeaheads list without having to type ?

(my goal is to create an advanced search bar like the one on Slack, Zoho... a search bar that suggests the possibilities !

Thanks.

**Comment by SaiSurya9999** [comment]
I am glad you liked it 🙂.

Could you please elaborate your request feature ? Actually this is tag input right where user types something and hits enter then it will be shown as a tag in the text area. According to your use case you trying to take a search input which will always be a single input. But the package provided area is for multi input. 

I understood that you want this feature to be configurable to single input with onFocus suggestions. This is a very good idea will work on it and keep you posted. If you want to contribute this feature to the source code you are welcome.

**Comment by redasakhi** [comment]
The idea is to have more events (like onFocus, onBlur, onSelect..) and the possibility to use custom template (ng-template) :
For example onFocus or onKeyup after typing "abc" : Open a dropdown of possible options : 
- contains:"abc"
- startswith:"abc"
- from:"abc"
- to:"abc"
And onSelect it adds [from:"abc"] as a tag and we can trigger some function..

**Comment by SaiSurya9999** [comment]
Major release is scheduled this weekend. Will update this issue in that release. Thank you :)

**Comment by SaiSurya9999** [comment]
New version of the package has been released with the requested enhancement. onFocus event added and also initial options are now configurable. 
Sorry for the delayed response. :)
Link: https://www.npmjs.com/package/ngconf-taginput
